docs/privacy-notice/latest.md

- PORT-3620: Test trigger with changes
- PORT-3620: Test trigger with changes

PORT-3620: Test notifications

---

docs/privacy-notice/latest.md

Reverts Fiserv/developer-studio-support#16

Revert "PORT-3620: Test notifications"

---

docs/terms-of-use/latest.md

Reverts Fiserv/developer-studio-support#18

Revert "Update latest.md"

---

docs/release-notes/2022/april.md
docs/release-notes/2022/february.md
docs/release-notes/2022/january.md
docs/release-notes/2022/june.md
docs/release-notes/2022/march.md
docs/release-notes/2022/may.md

Update RN format for dates to be part of page navigation.

Rn format change

---

docs/release-notes/2022.md

Sync RN from develop to stage

---

docs/release-notes/2022.md
docs/terms-of-use.md

Stage to main

---

docs/release-notes/2022.md

Add RN for Oct-27-2022 to stage branch.

Add RN for Oct-27-2022

---

config/document-explorer-definition.yaml
docs/search-and-catalog.md

Directory to Catalog update

---

config/document-explorer-definition.yaml
docs/release-notes/2023.md

Release Notes

---

docs/docs-firstdata-migration
docs/release-notes/2023.md

Release Notes Feb 2, 2023

---

docs/docs-firstdata-migration
docs/release-notes/2023.md

Release notes for Feb2,2023

---

config/document-explorer-definition.yaml

https://firstdatateam.atlassian.net/browse/PORT-7127
from above: 
Changed on dev:

PORT-7127: Update support page left nav

---

docs/md/basic-syntax.md

Support page working accordingly, adding footer color for QA testing references.

PORT-8069: Footer color

---

docs/about-developer-studio.md
docs/api-glossary.md

Revert back TEST text for 2 files to test web hooks

Web hook test

---

email-templates/credentials-added.template

testing to see if the product name can be displayed in the email

trying to add product name in the template body

---

email-templates/credentials-added.template

giving user instruction if they did not initial the operations

credentials-added template updates

---

email-templates/credentials-added.template

update <a> in credentials-added.template

update template anchor for credentials-added.template

---

email-templates/doc-request-approved.template
email-templates/doc-request-denied.template

https://firstdatateam.atlassian.net/browse/PORT-8929

PORT-8929: Gated Content (EMAIL) Adding UserName

---

email-templates/Client360/test-support.template

Add a Client360 template for testing purposes

PORT-9259: Add Client360 test template

---

email-templates/Client360/email-to-c360.template

Reverts Fiserv/developer-studio-support#214

Revert "Update email-to-c360.template"

---

docs/md/basic-syntax.md

PORT-10020: Blockquote color changes

---

email-templates/access-code-used.template
email-templates/card-developer-api-key-approval.template
email-templates/card-developer-api-key-verdict.template
email-templates/card-developer-webhook-approval.template
email-templates/card-developer-webhook-change-notification.template
email-templates/card-developer-webhook-create-notification.template
email-templates/card-developer-webhook-verdict.template
email-templates/ch-expiry-0.template
email-templates/ch-expiry-n.template
email-templates/credentials-added.template
email-templates/deleted-user.template
email-templates/doc-access-denied.template
email-templates/doc-access-request.template
email-templates/doc-request-acknowledgment.template
email-templates/doc-request-approved.template
email-templates/doc-request-denied.template
email-templates/inactive-0.template
email-templates/inactive-n.template
email-templates/privacy-notice-update.template
email-templates/profile-update.template
email-templates/pw-expiry-0.template
email-templates/pw-expiry-n.template
email-templates/request-access-code.template
email-templates/tou-update.template
email-templates/updates-to-file-subscription.template
email-templates/updates-to-subscription.template
email-templates/verify-email.template
email-templates/workspace-shared.template

Update all email-templates: icon, style, structure.

Oz fs patch 2

---

email-templates/doc-access-request.template
email-templates/doc-request-acknowledgment.template
email-templates/doc-request-approved.template
email-templates/doc-request-denied.template

replace margin-bottom with padding

updated template

---

docs/terms-of-use.md

cherry-pick terms of use update

---

email-templates/Client360/email-to-c360-client.template
email-templates/Client360/email-to-c360.template

c360 email template update

---

email-templates/temp.template

temporary template with no period in substitutions

PORT-11675: test temp template

---

email-templates/potential-unauthorized-access.template
java-email-templates/potential-unauthorized-access.template

TFDS-433: Add potential-unauthorized-access.template

TFDS-433: Add potential-unauthorized-access.template

---

email-templates/potential-unauthorized-access.template
java-email-templates/potential-unauthorized-access.template

TFDS-433: Update potential-unauthorized-access-email-template

---

email-templates/potential-unauthorized-access.template
java-email-templates/potential-unauthorized-access.template

TFDS-433: Update potential-unauthorized-access email template

---

email-templates/create-ai-assistant-failed.template
email-templates/create-ai-assistant-success.template
java-email-templates/create-ai-assistant-failed.template
java-email-templates/create-ai-assistant-success.template

TFDS-1331: Adding chatbot factory creation result email templates

TFDS-1331: Adding chatbot factory creation result email templates

---

docs/md/internal-release-notes.md
docs/release-notes/2024.md

Added internal release notes (hidden, can only be accessed via direct link), and added release notes for Sprint#14

Release Notes + Internal Release Notes

---

email-templates/leave-workspace.template
email-templates/removed-user-workspace.template
java-email-templates/leave-workspace.template
java-email-templates/removed-user-workspace.template

Added email templates for leaving workspace and being removed from workspace

---

email-templates/create-ai-assistant-success.template
java-email-templates/create-ai-assistant-success.template

TFDS-1800: Add APIUrl to chatbot factory success email

TFDS-1800: Add APIUrl to chatbot factory success email

---

email-templates/create-ai-assistant-update.template
java-email-templates/create-ai-assistant-update.template

Added chatbot factory update email template

TFDS-1945: Added chatbot factory update email template

---

email-templates/create-ai-assistant-failed.template
email-templates/create-ai-assistant-success.template
email-templates/create-ai-assistant-update.template
java-email-templates/create-ai-assistant-failed.template
java-email-templates/create-ai-assistant-success.template
java-email-templates/create-ai-assistant-update.template

Added assistant id into all AI assistant email templates

TFDS-1957: AI Assistant webhook email should include assistant_id

---

email-templates/create-ai-assistant-update.template
java-email-templates/create-ai-assistant-update.template

TFDS-1958: Format AI Assistant update email template

TFDS-1958: Format AI Assistant update email template

---

email-templates/create-ai-assistant-update.template
java-email-templates/create-ai-assistant-update.template

TFDS-1958: Format AI Assistant update html email template

TFDS-1958: Format AI Assistant update html email template

---

email-templates/create-ai-assistant-update.template
java-email-templates/create-ai-assistant-update.template

TFDS-1958: Update AI Assistant html email template

TFDS-1958: Update AI Assistant html email template

---

email-templates/create-ai-assistant-update.template
java-email-templates/create-ai-assistant-update.template

TFDS-1958: Update AI Assistant html email template table styling

TFDS-1958: Update AI Assistant html email template table styling

---

java-email-templates/role-changed-ai-assistant.template

Added a new template for user role change on AI Assistant Workspace

TFDS-2243: Create New Email Template For AI Assistant

---

README.md
docs/md/internal-release-notes.md
docs/release-notes/2024.md

Update external and internal release notes.

Update release notes for Release 11/07
